Created a ComponentListTemplate extension to enable sorting
Supershift/Sushi.Mediakiwi pull request #84
Opened 2021-08-20 10:43 UTC by TRoZZNL

- Sorting is re-enabled within an extension method.
- Fixed the JS sorting button bug, which would fire twice and show enabled -> disabled .
- Removed Slip package dependancy from the Grunt Bundle.

@marcmolenwijk a new CDN package should be created for the Bundle.

2021-08-24 06:21 UTC, bart-van-der-drift commented on src/Sushi.Mediakiwi.Files/gruntfile.js
> +                            /*'compiled/slip.min.js',*/
Please remove commented out code

2021-08-24 06:22 UTC, bart-van-der-drift commented on src/Sushi.Mediakiwi.Files/gruntfile.js
> +                           /* 'compiled/slip.min.js',*/
Please remove commented out code

2021-08-24 06:22 UTC, bart-van-der-drift commented on src/Sushi.Mediakiwi.Files/responsive/list.shtml
> +	<!--<script type="text/javascript" src="//az609478.vo.msecnd.net/6-25/scripts/slip.js"></script>-->
Please remove commented out code

2021-08-24 06:22 UTC, bart-van-der-drift commented on src/Sushi.Mediakiwi.Files/responsive/test.shtml
> +	<!--<script type="text/javascript" src="//az609478.vo.msecnd.net/6-25/scripts/slip.js"></script>-->
Please remove commented out code

2021-08-24 06:24 UTC, bart-van-der-drift requested changes
Please see comments

2021-09-01 05:51 UTC, TRoZZNL commented on src/Sushi.Mediakiwi.Files/gruntfile.js
> +                            /*'compiled/slip.min.js',*/
Done

2021-09-01 05:51 UTC, TRoZZNL commented on src/Sushi.Mediakiwi.Files/responsive/list.shtml
> +	<!--<script type="text/javascript" src="//az609478.vo.msecnd.net/6-25/scripts/slip.js"></script>-->
Done

2021-09-01 05:51 UTC, TRoZZNL commented on src/Sushi.Mediakiwi.Files/responsive/test.shtml
> +	<!--<script type="text/javascript" src="//az609478.vo.msecnd.net/6-25/scripts/slip.js"></script>-->
Done

2021-09-01 07:35 UTC, bart-van-der-drift approved these changes

2021-09-07 06:12 UTC, merged